### ISSUE TITLE
Usepe Plugin crashes when destination or origin of a drone is not in a defined segment

### ISSUE THREAD

**Issue by joakimrydberg** [USEPE-SesarJU/bluesky#21]
In a few methods `(processFlightPlans():829, reprocessFlightPlans():873, UsepeSegments.preupdate():388)` the origin and destination of a drone is checked in case it's in a no fly zone.
However, if either of those points are not in any mapped segment (`cond` is an empty list) then the segment name is set to `'N/A'`. This is not a valid segment name, which means that a couple of lines further down when attempting to check the max speed of the segment the process crashes with a KeyError.
This can happen for background drones which have their origins and destinations randomly assigned.

Rather than setting the segment name to `'N/A'` this has to be handled differently.
Maybe, simply dropping the flight plan from the buffer in the same way as is done if the max speed is 0?

**Comment by jbueno-nommon** [comment]
@joakimrydberg Initially, I included a segment named `'N/A'` with velocity 0 and capacity 0 to be assigned to all nodes and edges outside the segment region. Now, the segments are created by the segmentation service developed by DLR, and this additional segment is not defined (it could be added).

We can use the approach that you mention: to drop the flight plan when the origin/destination is not inside any segment. This will solve the bug in the code, but there may be a deeper error:

- Does it make sense to have drones that depart/arrives outside the segments? As I understand D2-C2, the segments cover the entire airspace. Why do you have a drone that departs/arrives outside the segments? Is your study area larger than the segment region?

**Comment by jbueno-nommon** [comment]
It is solved in the commit: [6b5710ca0e11263f8ee980affe2effbe066b44d9](https://github.com/USEPE-SesarJU/bluesky/commit/6b5710ca0e11263f8ee980affe2effbe066b44d9)

If the origin or destination of a drone is not within any segment (i.e., the segment name is set to `'N/A'`), the flight plan is dropped from the buffer (i.e., the drone is not included in the simulation).

**Comment by oledahle** [comment]
This is still a problem when running the graph creation workbook for exercise 3 (scenario/USEPE/exercise_3/exe_3_graph_creation.ipynb on the exercise_3 branch of scenarios). It fails with a keyError inside updateSegmentVelocity() in dymaic_segments.py.
Attached is a proposed change in updateSegmentVelocity() to assign default velocity to edge if it is not in a segment.

Output from error below:
--------
Updating segment velocity...

KeyError                                  Traceback (most recent call last)
File ~/.conda/envs/usepeosm/lib/python3.8/site-packages/pandas/core/indexes/base.py:3621, in Index.get_loc(self, key, method, tolerance)
   3620 try:
-> 3621     return self._engine.get_loc(casted_key)
   3622 except KeyError as err:

File ~/.conda/envs/usepeosm/lib/python3.8/site-packages/pandas/_libs/index.pyx:136, in pandas._libs.index.IndexEngine.get_loc()

File ~/.conda/envs/usepeosm/lib/python3.8/site-packages/pandas/_libs/index.pyx:144, in pandas._libs.index.IndexEngine.get_loc()

File pandas/_libs/index_class_helper.pxi:41, in pandas._libs.index.Int64Engine._check_type()

KeyError: 'N/A'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
/home/oda/ws/scenarios/scenario/USEPE/exercise_3/exe_3_graph_creation.ipynb Cell 13 in <cell line: 5>()
      [1](vscode-notebook-cell:/home/oda/ws/scenarios/scenario/USEPE/exercise_3/exe_3_graph_creation.ipynb#X15sZmlsZQ%3D%3D?line=0) # ---------------- 5. Segment update --------------------
      [2](vscode-notebook-cell:/home/oda/ws/scenarios/scenario/USEPE/exercise_3/exe_3_graph_creation.ipynb#X15sZmlsZQ%3D%3D?line=1) """
      [3](vscode-notebook-cell:/home/oda/ws/scenarios/scenario/USEPE/exercise_3/exe_3_graph_creation.ipynb#X15sZmlsZQ%3D%3D?line=2) Once we have loaded the segments and we created the corridors, we update the graph based on the parameters of the segments
      [4](vscode-notebook-cell:/home/oda/ws/scenarios/scenario/USEPE/exercise_3/exe_3_graph_creation.ipynb#X15sZmlsZQ%3D%3D?line=3) """
----> [5](vscode-notebook-cell:/home/oda/ws/scenarios/scenario/USEPE/exercise_3/exe_3_graph_creation.ipynb#X15sZmlsZQ%3D%3D?line=4) G, segments = dynamicSegments( G, config, segments, deleted_segments=None )
...
   3626     #  InvalidIndexError. Otherwise we fall through and re-raise
   3627     #  the TypeError.
   3628     self._check_indexing_error(key)

KeyError: 'N/A'
--
[dynamic_segments.py.diff.txt](https://github.com/USEPE-SesarJU/bluesky/files/9496502/dynamic_segments.py.diff.txt)

**Comment by oledahle** [comment]
Also fails in checkIfNoFlyZone() in usepe/city_model/utils.py when running the CSV flightplan creation workbook (scenario/USEPE/exercise_3/case_study_csv_file_generator.ipynb on the exercise_3 branch of scenarios).  It fails with
valuerror in utils.py, line 158. (Note that the point is randomy placed, so this does not happen immediately, but usually before all 150 flights have been generated!)

Attached is a proposed change in checkIfNoFlyZone() that returns false if the point is not in any segment.
[utils.py.diff.txt](https://github.com/USEPE-SesarJU/bluesky/files/9496712/utils.py.diff.txt)

Output from error below:
 Creating background traffic...
Creating flight 1...
Creating flight 2...
Creating flight 3...
Creating flight 4...
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/home/oda/ws/scenarios/scenario/USEPE/exercise_3/case_study_csv_file_generator.ipynb Cell 12 in <cell line: 7>()
      [5](vscode-notebook-cell:/home/oda/ws/scenarios/scenario/USEPE/exercise_3/case_study_csv_file_generator.ipynb#X14sZmlsZQ%3D%3D?line=4) # Add background traffic
      [6](vscode-notebook-cell:/home/oda/ws/scenarios/scenario/USEPE/exercise_3/case_study_csv_file_generator.ipynb#X14sZmlsZQ%3D%3D?line=5) print('Creating background traffic...')
----> [7](vscode-notebook-cell:/home/oda/ws/scenarios/scenario/USEPE/exercise_3/case_study_csv_file_generator.ipynb#X14sZmlsZQ%3D%3D?line=6) createBackgroundTrafficCSV(density['Medium'], avg_flight_duration, simulation_time, G, segments, config)

File ~/ws/bluesky/usepe/city_model/scenario_definition.py:1243, in createBackgroundTrafficCSV(density, avg_flight_duration, simulation_time, G, segments, config)
   1240     continue
   1242 # Check if the origin or destination is in a restricted area (spd = 0)
-> 1243 if checkIfNoFlyZone( orig_lat, orig_lon, None, G, segments ):
   1244     continue
   1245 if checkIfNoFlyZone( dest_lat, dest_lon, None, G, segments ):

File ~/ws/bluesky/usepe/city_model/utils.py:158, in checkIfNoFlyZone(lat, lon, alt, G, segments)
    156 else:
    157     nearest_node = nearestNode3d( G, lon, lat, alt )
--> 158 speed = segments.loc[int( G.nodes[nearest_node]['segment'] )]['speed_max']
    159 cap = segments.loc[int( G.nodes[nearest_node]['segment'] )]['capacity']
    160 if speed == 0:

ValueError: invalid literal for int() with base 10: 'N/A'

**Comment by mbaena-nommon** [comment]
I have included your changes in the last commit [7ea425729593849941ae3a128040aa5e15752498](https://github.com/USEPE-SesarJU/bluesky/commit/7ea425729593849941ae3a128040aa5e15752498). I have modify it so it returns True when the point is not in any segment ('NA'). 

The reason is that, when this function returns True, the route in question is skipped in subsequent stages of the code. If it returns False, it will eventually crash since it needs the information of the segment in which it starts/ends.

**Comment by oledahle** [comment]
Works now! Closing issue.

**Comment by joakimrydberg** [comment]
Just some final comments.

After digging around I found a couple of reasons for why we did get the `'N/A'` segments in the first place:
- As detailed in #22 the background traffic lacked altitude information. Can someone verify if my fix is suitable or needs adjustment?
- In some areas we lack segments under a certain altitude. This is likely the same issue that Jerónimo detailed in an email, which should be solved by the proposed change to the segmentation service.
- As suggested by Jerónimo, the mapped segments do not fully cover our area of study. I created a new issue for this here #23

**Comment by mbaena-nommon** [comment]
Hi Joakim,

About your comments:

   - As detailed in #22
<https://github.com/USEPE-SesarJU/bluesky/issues/22> the
   background traffic lacked altitude information. Can someone verify if my
   fix is suitable or needs adjustment?
      - I added a fix to randomly select the altitude between 0 and the
      maximum building height.
   - In some areas we lack segments under a certain altitude. This is
   likely the same issue that Jerónimo detailed in an email, which should be
   solved by the proposed change to the segmentation service.
      - This issue was fixed by Rostislav in the following commit:
      https://github.com/USEPE-SesarJU/bluesky/commit/f46bb79218ce25000720e9affc8342c1e61b985e
   - As suggested by Jerónimo, the mapped segments do not fully cover our
   area of study. I created a new issue for this here #23
   <https://github.com/USEPE-SesarJU/bluesky/issues/23>
      - Different regions can be selected for the initial segmentation.
      Please, @Rostislav, let us know if any other region fits the boundaries
      included in the issue or if it is possible to create a new region to fit
      Indra's study domain.

Best regards,
Miguel
---------------------------------------------------------------------------
-------

*Miguel Baena*

Aviation Consultant

Nommon Solutions and Technologies

Plaza Carlos Trías Bertrán 4, 2ª planta. 28020 Madrid, Spain

Tel: +34 911 860 075

www.nommon.es | Twitter <https://twitter.com/_nommon> | LinkedIn
<https://www.linkedin.com/company/nommon-solutions-and-technologies/>
<https://twitter.com/_nommon>
---------------------------------------------------------------------------
-------

Los datos de contacto utilizados para la presente comunicación son tratados
por Nommon Solutions and Technologies S.L., con CIF B86440906, con la
finalidad de posibilitar las comunicaciones a través de correo electrónico
que ésta mantiene dentro del ejercicio de su actividad de conformidad al
Reglamento UE 2016/679 relativo a la Protección de las Personas Físicas en
lo que Respecta al Tratamiento de Datos Personales y a la Libre Circulación
de estos Datos y a la normativa vigente en la materia. Le recordamos la
posibilidad de ejercer los derechos de acceso, rectificación, supresión,
oposición, portabilidad y limitación del tratamiento mediante escrito de
solicitud acompañando copia de su documento de identidad dirigido al
Responsable de Tratamiento, Nommon Solutions and Technologies S.L., en
Plaza Carlos Trías Bertrán 4, 2ª planta, 28020 Madrid, España, o a través
de la dirección de correo electrónico ***@***.*** Asimismo, Nommon pone
a disposición de los interesados, a través de su página web, su Política de
Privacidad, en la que se ofrece información más detallada y completa sobre
el tratamiento que realiza sobre los datos de carácter personal. La
información contenida en este e-mail va dirigida únicamente a su
destinatario y podría contener información confidencial. Si usted no es el
destinatario indicado, no debe copiar, distribuir, o llevar a cabo ninguna
acción con el mismo. Si hubiera recibido este e-mail por error, por favor
comuníquelo inmediatamente por e-mail a ***@***.***
